require('dotenv').config();
const mongoose = require('mongoose');
const Course = require('./models/Course'); // path tới model Course

const courseList = [
  {
    title: "Interior Design Basics",
    image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-2-800x488.jpg",
    instructor: "Lan Do",
    category: "University",
    rating: 4.5,
    lessons: 12,
    students: 1230,
    duration: "3 Weeks",
    level: "Beginner",
    price: 0,
    publishedAt: new Date("2025-06-01"),
    isFeatured: true,
    description: "Learn the fundamentals of interior design from scratch."
  },
  {
    title: "Color Theory in Design",
    image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
    instructor: "Thanh Nguyen",
    category: "Private",
    rating: 4.8,
    lessons: 10,
    students: 945,
    duration: "2 Weeks",
    level: "Beginner",
    price: 49,
    publishedAt: new Date("2025-06-10"),
    isFeatured: true,
    description: "Master the use of color to enhance interior spaces."
  },
  {
    title: "Advanced Furniture Layout",
    image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
    instructor: "Minh Chau",
    category: "University",
    rating: 4.6,
    lessons: 15,
    students: 890,
    duration: "4 Weeks",
    level: "Intermediate",
    price: 69,
    publishedAt: new Date("2025-06-15"),
    isFeatured: false,
    description: "Create optimal furniture layouts for any room type."
  },
  {
    title: "Small Space Makeover",
    image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
    instructor: "Huy Tran",
    category: "Studio",
    rating: 4.3,
    lessons: 8,
    students: 720,
    duration: "2 Weeks",
    level: "All levels",
    price: 0,
    publishedAt: new Date("2025-06-18"),
    isFeatured: false,
    description: "Learn to transform tight spaces into cozy homes."
  },
  {
    title: "Minimalist Home Design",
    image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
    instructor: "Anna Tran",
    category: "Private",
    rating: 4.9,
    lessons: 10,
    students: 1450,
    duration: "3 Weeks",
    level: "Intermediate",
    price: 79,
    publishedAt: new Date("2025-06-20"),
    isFeatured: true,
    description: "Embrace minimalism in every corner of your home."
  },
  {
    title: "Decorating with Plants",
    image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
    instructor: "Thanh Nguyen",
    category: "Home",
    rating: 4.7,
    lessons: 6,
    students: 630,
    duration: "1 Week",
    level: "Beginner",
    price: 0,
    publishedAt: new Date("2025-06-22"),
    isFeatured: false,
    description: "Use greenery to create relaxing and vibrant interiors."
  },
  {
    title: "Professional Lighting Design",
    image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
    instructor: "Lan Do",
    category: "Shop",
    rating: 4.8,
    lessons: 12,
    students: 880,
    duration: "2 Weeks",
    level: "Advanced",
    price: 99,
    publishedAt: new Date("2025-06-25"),
    isFeatured: false,
    description: "Light up spaces like a pro for commercial or residential needs."
  },
  {
    title: "Vintage Interior Styling",
    image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
    instructor: "Huy Tran",
    category: "Home",
    rating: 4.2,
    lessons: 7,
    students: 410,
    duration: "1 Week",
    level: "All levels",
    price: 39,
    publishedAt: new Date("2025-06-26"),
    isFeatured: false,
    description: "Bring timeless elegance to modern homes using vintage styles."
  },
  {
    title: "Kitchen Design Masterclass",
    image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
    instructor: "Minh Chau",
    category: "Home",
    rating: 4.6,
    lessons: 9,
    students: 780,
    duration: "2 Weeks",
    level: "Intermediate",
    price: 59,
    publishedAt: new Date("2025-06-28"),
    isFeatured: false,
    description: "Plan and design the perfect kitchen layout and decor."
  },
  {
    title: "Bohemian Style Interiors",
    image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
    instructor: "Anna Tran",
    category: "Studio",
    rating: 4.5,
    lessons: 10,
    students: 670,
    duration: "2 Weeks",
    level: "All levels",
    price: 29,
    publishedAt: new Date("2025-06-30"),
    isFeatured: true,
    description: "Use eclectic elements to craft unique and artistic rooms."
  },
  {
  title: "Scandinavian Home Design",
  image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
  instructor: "Thanh Nguyen",
  category: "Private",
  rating: 4.7,
  lessons: 14,
  students: 1020,
  duration: "3 Weeks",
  level: "Intermediate",
  price: 89,
  publishedAt: new Date("2025-07-01"),
  isFeatured: false,
  description: "Bring warmth and simplicity with Scandinavian aesthetics."
},
{
  title: "3D Interior Visualization",
  image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
  instructor: "Lan Do",
  category: "University",
  rating: 4.9,
  lessons: 20,
  students: 1145,
  duration: "5 Weeks",
  level: "Expert",
  price: 129,
  publishedAt: new Date("2025-07-02"),
  isFeatured: true,
  description: "Master the tools to visualize your interior design ideas in 3D."
},
{
  title: "Japanese Zen Interiors",
  image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
  instructor: "Minh Chau",
  category: "Home",
  rating: 4.4,
  lessons: 10,
  students: 840,
  duration: "2 Weeks",
  level: "Beginner",
  price: 69,
  publishedAt: new Date("2025-07-03"),
  isFeatured: false,
  description: "Create peace and balance in your home with Zen philosophy."
},
{
  title: "Basic SketchUp for Designers",
  image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
  instructor: "Thanh Nguyen",
  category: "University",
  rating: 4.4,
  lessons: 10,
  students: 740,
  duration: "2 Weeks",
  level: "Beginner",
  price: 0,
  publishedAt: new Date("2025-07-15"),
  isFeatured: false,
  description: "Get started with 3D design using SketchUp for interior projects."
},
{
  title: "Luxury Home Interiors",
  image: "https://images.unsplash.com/photo-1550581190-9c1c48d21d6c",
  instructor: "Lan Do",
  category: "Private",
  rating: 4.9,
  lessons: 18,
  students: 1980,
  duration: "4 Weeks",
  level: "Expert",
  price: 99,
  publishedAt: new Date("2025-06-10"),
  isFeatured: true,
  description: "Design opulent spaces with high-end finishes and furniture."
},
{
  title: "Retail Lighting Techniques",
  image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
  instructor: "Anna Tran",
  category: "Shop",
  rating: 5.0,
  lessons: 17,
  students: 520,
  duration: "2 Weeks",
  level: "All levels",
  price: 69,
  publishedAt: new Date("2025-05-03"),
  isFeatured: true,
  description: "Use lighting to enhance retail ambiance and product visibility."
},
{
  title: "Creative Studio Spaces",
  image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
  instructor: "Anna Tran",
  category: "Studio",
  rating: 4.5,
  lessons: 8,
  students: 873,
  duration: "1 Week",
  level: "Intermediate",
  price: 89,
  publishedAt: new Date("2025-07-11"),
  isFeatured: false,
  description: "Explore the creative possibilities of compact studio living."
},
{
  title: "Modern Apartment Styling",
  image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
  instructor: "Anna Tran",
  category: "Private",
  rating: 4.9,
  lessons: 13,
  students: 931,
  duration: "4 Weeks",
  level: "Beginner",
  price: 49,
  publishedAt: new Date("2025-06-09"),
  isFeatured: false,
  description: "Style modern apartments with practical and aesthetic design solutions."
},
{
  title: "Eco-Friendly Interiors",
  image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
  instructor: "Huy Tran",
  category: "Home",
  rating: 4.8,
  lessons: 11,
  students: 790,
  duration: "2 Weeks",
  level: "All levels",
  price: 59,
  publishedAt: new Date("2025-06-12"),
  isFeatured: true,
  description: "Design sustainable and eco-conscious interior environments."
},
{
  title: "Textile Selection for Interiors",
  image: "https://images.unsplash.com/photo-1558002038-1055907df827",
  instructor: "Minh Chau",
  category: "University",
  rating: 4.3,
  lessons: 6,
  students: 410,
  duration: "1 Week",
  level: "Intermediate",
  price: 39,
  publishedAt: new Date("2025-06-30"),
  isFeatured: false,
  description: "Choose fabrics and materials that elevate interior appeal."
},
{
  title: "Scandinavian Style Essentials",
  image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
  instructor: "Cam Tu",
  category: "Private",
  rating: 4.7,
  lessons: 15,
  students: 1120,
  duration: "3 Weeks",
  level: "Intermediate",
  price: 49,
  publishedAt: new Date("2025-05-20"),
  isFeatured: false,
  description: "Master the minimalist and functional approach of Scandinavian interiors."
},
{
  title: "Advanced AutoCAD Drafting",
  image: "https://images.unsplash.com/photo-1523413651479-597eb2da0ad6",
  instructor: "Duy Tran",
  category: "University",
  rating: 4.8,
  lessons: 20,
  students: 1680,
  duration: "5 Weeks",
  level: "Expert",
  price: 129,
  publishedAt: new Date("2025-06-25"),
  isFeatured: true,
  description: "Take your drafting skills to the next level with advanced AutoCAD techniques."
},
{
  title: "Children's Room Design",
  image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
  instructor: "Linh Dang",
  category: "Community",
  rating: 4.2,
  lessons: 9,
  students: 530,
  duration: "2 Weeks",
  level: "Beginner",
  price: 0,
  publishedAt: new Date("2025-04-18"),
  isFeatured: false,
  description: "Learn to design fun, functional, and safe spaces for children."
},
{
  title: "Mid-Century Modern Interiors",
  image: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
  instructor: "Minh Chau",
  category: "Private",
  rating: 4.6,
  lessons: 14,
  students: 890,
  duration: "3 Weeks",
  level: "Intermediate",
  price: 65,
  publishedAt: new Date("2025-06-01"),
  isFeatured: true,
  description: "Capture the essence of the 1950s–60s with sleek furniture and retro aesthetics."
},
{
  title: "Green Building and Eco Design",
  image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
  instructor: "Ngoc Mai",
  category: "University",
  rating: 4.9,
  lessons: 22,
  students: 2040,
  duration: "6 Weeks",
  level: "Expert",
  price: 149,
  publishedAt: new Date("2025-07-01"),
  isFeatured: true,
  description: "Build sustainable and energy-efficient designs for the future."
},
{
  title: "Home Office Design Tips",
  image: "https://images.unsplash.com/photo-1593642532973-d31b6557fa68",
  instructor: "Hung Bui",
  category: "Community",
  rating: 4.1,
  lessons: 8,
  students: 450,
  duration: "1 Week",
  level: "Beginner",
  price: 0,
  publishedAt: new Date("2025-05-05"),
  isFeatured: false,
  description: "Design productive and ergonomic workspaces at home."
},
{
  title: "Color Psychology in Interiors",
  image: "https://edupress.thimpress.com/wp-content/uploads/2023/01/new-art-course-3-800x488.jpg",
  instructor: "Thu Ha",
  category: "University",
  rating: 4.7,
  lessons: 12,
  students: 970,
  duration: "2 Weeks",
  level: "Intermediate",
  price: 79,
  publishedAt: new Date("2025-07-10"),
  isFeatured: true,
  description: "Understand how color choices impact emotions and behavior in design."
},
{
  title: "Japanese Zen Interior Design",
  image: "https://edupress.thimpress.com/wp-content/uploads/2024/01/create-an-lms-website-with-learnpress-5-1-800x488.jpg",
  instructor: "Hieu Le",
  category: "Private",
  rating: 4.5,
  lessons: 11,
  students: 780,
  duration: "3 Weeks",
  level: "Intermediate",
  price: 59,
  publishedAt: new Date("2025-06-18"),
  isFeatured: false,
  description: "Embrace tranquility and minimalism with Japanese design aesthetics."
},
{
  title: "Bathroom Renovation Basics",
  image: "https://edupress.thimpress.com/wp-content/uploads/2024/01/create-an-lms-website-with-learnpress-5-1-800x488.jpg",
  instructor: "Trang Pham",
  category: "Community",
  rating: 4.3,
  lessons: 10,
  students: 600,
  duration: "2 Weeks",
  level: "Beginner",
  price: 0,
  publishedAt: new Date("2025-07-05"),
  isFeatured: false,
  description: "Get hands-on advice for planning and renovating bathrooms."
},
{
  title: "Interior Photography for Designers",
  image: "https://edupress.thimpress.com/wp-content/uploads/2024/01/create-an-lms-website-with-learnpress-5-1-800x488.jpg",
  instructor: "Quang Nguyen",
  category: "University",
  rating: 4.6,
  lessons: 16,
  students: 990,
  duration: "4 Weeks",
  level: "Intermediate",
  price: 89,
  publishedAt: new Date("2025-06-30"),
  isFeatured: true,
  description: "Learn to capture interiors effectively for portfolios and marketing."
}

];

// ===== Seed Script =====
async function seedCourses() {
  try {
    await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/edupress', {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('MongoDB connected');

    await Course.deleteMany(); // xóa data cũ nếu có
    const inserted = await Course.insertMany(courseList);
    console.log(`Inserted ${inserted.length} courses`);

    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seedCourses();
